import Head from 'next/head'
import { useDomains } from '../hooks/useDomains'


export default function domains() {
    const {domains, loading} = useDomains();

    return (
        <div>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

            {loading ? "Loading" : JSON.stringify(domains)}
          
         
        </div>
      )
}
